version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    command:
      - --collector.systemd
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./alert/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    environment:
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
    volumes:
      - ./alert/alertmanager.yml.tpl:/etc/alertmanager/alertmanager.yml.tpl:ro
      - ./alert/entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
